### ISSUE TITLE
Inconsistent results with previous works

### ISSUE THREAD

**Issue by MohammadHossein-Bahari** [haizhongzheng/Coverage-centric-coreset-selection#1]
Hello,

Thanks for the great work and I hope you release the final code soon!
I wonder why the numbers you report for Forgetting in high pruning rates (e.g., figure 1 of the paper) do not match with the results in Deepcore library (Table 1, in this paper [Link](https://arxiv.org/pdf/2204.08499.pdf)). While the other baselines are consistent, there is a huge difference between the reported numbers of Forgetting paper.

Thank you very much.

**Comment by haizhongzheng** [comment]
Hi Mohammadhossein,

Thanks for your interest in our work and bringing this up for discussion!

It seems that the forgetting method implemented in the DeepCore paper does not experience an accuracy drop at high pruning rates.

However, our evaluation results are consistent with other research papers: For example, Figure 6 in the original forgetting paper[1] and Figure 2 in another recent coreset paper[2], which all show the accuracy drop at high pruning rates.

[1] Toneva, Mariya, et al. "An empirical study of example forgetting during deep neural network learning." arXiv preprint arXiv:1812.05159 (2018).
[2] Xia, Xiaobo, et al. "Moderate coreset: A universal method of data selection for real-world data-efficient deep learning." The Eleventh International Conference on Learning Representations. 2023.

Thanks
Haizhong
